# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3abc799e6ce72ce425c2388c007611465cdfa69c4d1c21887e67969ddc89aead7fbd6d26a7453815755376d653292aa5f55bb611b0c6b59ea8bffe21395ed0be

test:
  secret_key_base: bf9d75551008788ec1df1fe58f429b472a99254c8b7efabf4f637e0faf25df3ec62ab71b35dd916517a8fad3fd7917eded5b8b929f84bc27bc2be12d8c474920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
